name: bmi_calculator
description: BMI Calculator

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/gender/
    - assets/images/age/
    - assets/images/height/

  fonts:
    - family: Catamaran
      fonts:
        - asset: assets/fonts/Catamaran-Bold.ttf
          weight: 700
        - asset: assets/fonts/Catamaran-Regular.ttf
        - asset: assets/fonts/Catamaran-Light.ttf
          weight: 300
        - asset: assets/fonts/Catamaran-Thin.ttf
          weight: 100
